### PR TITLE
Bail out of dispatching a listener in `useEventListenerOutside` when the document doesn't have focus

### LINKED ISSUE #619: Dialog closes unexpectedly on Firefox when using hideOnClickOutside
### Current behavior

If focus leaves the Firefox window, any action inside of the window afterwards causes the modal to close - even if this action is clicking inside the modal itself.

### Steps to reproduce the bug

Provide a repo or sandbox with the bug and describe the steps to reproduce it.

1. Open sandbox: https://codesandbox.io/s/reakit-firefox-hideonclickoutside-bug-3lm0t
2. Open the dialog
3. Give focus to outside of the preview window, either by clicking the codesandbox ui, another application window, or pressing a browser keyboard shortcut such as F6 to focus the address bar.
4. Click anywhere inside the modal or resize the window

### Expected behavior

Nothing should happen

### Possible solutions

TBD

### Environment

Firefox 76.0b4 (64-bit) Dev Edition
```sh
  System:
    OS: Linux 4.19 Ubuntu 18.04.4 LTS (Bionic Beaver)       
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   
    Memory: 12.09 GB / 12.37 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.2 - ~/.config/nvm/12.16.2/bin/node
    Yarn: 1.22.4 - /mnt/c/Program Files (x86)/Yarn/bin/yarn 
    npm: 6.14.4 - ~/.config/nvm/12.16.2/bin/npm
  npmPackages:
    reakit: ^1.0.0-rc.0 => 1.0.0-rc.0
```

### PR DESCRIPTION
**Pull request by tom-sherman**
Fixes #619

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by tom-sherman** [comment]
It appears that the reason this issue appears on Firefox and not Chrome is that on Firefox the focus event fires with document as the target (making the `contains(container, target)` evaluate to `true`), whereas in Chrome the focus is passed directly to the element that you have clicked on.

For resizing, focus events aren't fired in Chrome but they are in Firefox; again, with the target set to the document.

**Comment by tom-sherman** [comment]
You can verify that it's fixed using the first Modal example in the deploy preview: https://deploy-preview-620--reakit.netlify.com/docs/dialog/#usage

**Comment by diegohaz** [comment]
> You can verify that it's fixed using the first Modal example in the deploy preview: https://deploy-preview-620--reakit.netlify.com/docs/dialog/#usage

It seems that all clicks outside were disabled now. Tests are failing because of this.

> It appears that the reason this issue appears on Firefox and not Chrome is that on Firefox the focus event fires with document as the target (making the contains(container, target) evaluate to true), whereas in Chrome the focus is passed directly to the element that you have clicked on.
>
> For resizing, focus events aren't fired in Chrome but they are in Firefox; again, with the target set to the document.

So I guess the check should be `if (target === document) return;`.

File: packages/reakit/src/Dialog/__utils/useEventListenerOutside.ts [hunk 1]
```diff
@@ -58,6 +58,9 @@ export function useEventListenerOutside(
         return;
       }
 
+      // Fix for https://github.com/reakit/reakit/issues/619
+      if (document.hasFocus()) return;
```
Comment (diegohaz) [inline packages/reakit/src/Dialog/__utils/useEventListenerOutside.ts]: If it returns, it won't close the dialog. So this is basically saying that if anything in the document has focus, it shouldn't close the dialog.

Also, `document` should use the `document` constant that is defined below this handler function (just moving it before the function should be enough).

File: packages/reakit/src/Dialog/__utils/useEventListenerOutside.ts [hunk 2]
```diff
@@ -58,6 +58,15 @@ export function useEventListenerOutside(
...
       }
 
+      // Fix for https://github.com/reakit/reakit/issues/619
+      if (
+        event.type === "focus" &&
+        (target as any) === document &&
+        document.hasFocus()
+      ) {
+        return;
+      }
```
Comment (diegohaz) [inline packages/reakit/src/Dialog/__utils/useEventListenerOutside.ts]: If it's only on focus, I think the check should be actually done here: https://github.com/reakit/reakit/blob/db71535b4cdc4d7c88f7860d3a55b62202b845c8/packages/reakit/src/Dialog/__utils/useHideOnClickOutside.ts#L62

Click does a similar check: https://github.com/reakit/reakit/blob/db71535b4cdc4d7c88f7860d3a55b62202b845c8/packages/reakit/src/Dialog/__utils/useHideOnClickOutside.ts#L40-L55

Comment (tom-sherman) [reply packages/reakit/src/Dialog/__utils/useEventListenerOutside.ts]: That makes a lot of sense.

File: packages/reakit/src/Dialog/__utils/useHideOnClickOutside.ts [hunk 3]
```diff
@@ -47,19 +47,26 @@ export function useHideOnClickOutside(
...
-      if (mouseDownRef.current === event.target && options.hide) {
-        options.hide();
+      if (mouseDownRef.current === event.target) {
+        options.hide?.();
       }
     },
     options.visible && options.hideOnClickOutside
   );
 
+  const document = getDocument(dialogRef.current);
```
Comment (diegohaz) [inline packages/reakit/src/Dialog/__utils/useHideOnClickOutside.ts]: `dialogRef.current` may not be populated at the time the `useHideOnClickOutside` function is called, so this should be inside the event handler in this case (it could be outside the event handler on the other custom hook because it was still inside `useEffect`.

Comment (tom-sherman) [reply packages/reakit/src/Dialog/__utils/useHideOnClickOutside.ts]: It sounds like getDocument shouldn't accept null as a parameter in that case, should the type be changed? Looking at it's call sites, it currently only accepts null from getActiveElement, and getActiveElement's call sites don't pass in null either.

Comment (diegohaz) [reply packages/reakit/src/Dialog/__utils/useHideOnClickOutside.ts]: `getDocument` will return the current window's document as a fallback. My understanding is that that's safer as most people will not need the specific `element.ownerDocument` (as far as I know, only those using components inside of an iframe will need it).

But we can discuss it better on #456

Comment (tom-sherman) [reply packages/reakit/src/Dialog/__utils/useHideOnClickOutside.ts]: Ah ok, vscode missed a load of callsites where null unions were being passed in anyway so the change isn't as trivial as I first thought.

File: packages/reakit/src/Dialog/__utils/useHideOnClickOutside.ts [hunk 4]
```diff
@@ -47,8 +47,8 @@ export function useHideOnClickOutside(
       // triggered the mousedown event. This prevents the dialog from closing
       // by dragging the cursor (for example, selecting some text inside the
       // dialog and releasing the mouse outside of it).
-      if (mouseDownRef.current === event.target && options.hide) {
-        options.hide();
+      if (mouseDownRef.current === event.target) {
+        options.hide?.();
```
Comment (diegohaz) [inline packages/reakit/src/Dialog/__utils/useHideOnClickOutside.ts:51]: Nice 👍
