### PR TITLE
fix: Fix disclosure detection when `unstable_virtual` is `true` on React 17

### LINKED ISSUE #706: React 17 support
Thought I'd open this issue to track bugs related to React 17.

You can view the most recent CI run on `react@next` here: https://github.com/reakit/reakit/actions?query=workflow%3Areact-next+

There is some change in focus behaviour, see https://github.com/facebook/react/issues/19606

### PR DESCRIPTION
**Pull request by diegohaz**
Closes #706
Closes #707

When you click on a button that opens a `Dialog`, there's an internal `useDisclosureRef` hook that will try to detect which element had focus right before so it can return focus to it when the dialog closes.

This is true for all components that use `Dialog`, like `Menu`.

When `unstable_virtual` is `true`, [focus quickly moves between items and the container](https://twitter.com/diegohaz/status/1291006968103088129). This works well on React 16. But due to how DOM events propagate to `document` in React 17, this has stopped working.

Looks like listening to `focusin` events instead of capturing `focus` fixes this (see tests in first commit).

**How to test?**

Compare tests on the first commit in this PR (the one that is using React 17), that are passing, and the tests against React 17 on master: https://github.com/reakit/reakit/runs/991617903?check_suite_focus=true#step:9:281

**Does this PR introduce breaking changes?**

No

### CODE REVIEW

File: packages/reakit/src/Dialog/__utils/useEventListenerOutside.ts [hunk 1]
```diff
@@ -20,11 +20,7 @@ function dialogContains(target: Element) {
 }
 
 function isDisclosure(target: Element, disclosure: HTMLElement) {
-  if (contains(disclosure, target)) return true;
-  return (
-    disclosure.id &&
-    disclosure.id === target.getAttribute?.("aria-activedescendant")
-  );
+  return contains(disclosure, target);
 }
```
Comment (diegohaz) [inline packages/reakit/src/Dialog/__utils/useEventListenerOutside.ts:24]: Looks like this is not necessary anymore as now we're always capturing the right disclosure element, and not the container with `aria-activedescendant`. But I'll keep an eye on this.
