### PR TITLE
fix: Fix `Composite` state update on unmounted components

### LINKED ISSUE #650: Potential React warning triggered by useToolbarState
On Gutenberg when doing:

- Type `* ` on an empty paragraph
 - Click "cmd + z" to undo

It triggers a React warning with the following stack trace

Capture d’écran 2020-05-19 à 3 02 45 PM

And if I'm reading right, this is the only place where this could be triggered right?

https://github.com/WordPress/gutenberg/blob/692ec8cb40f8372484da4ddb8930fe4fecf6e8a7/packages/components/src/toolbar/toolbar-container.js#L20

### PR DESCRIPTION
**Pull request by diegohaz**
Closes #650

This is a very specific case where the state lives in a component, and you try to update it from another component that is not a descendant right after the former has been unmounted. This is only possible if you pass the state up to a component higher in the tree.

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

File: packages/reakit/src/Composite/CompositeState.ts [hunk 1]
```diff
@@ -579,6 +579,17 @@ function useAction<T extends (...args: any[]) => any>(fn: T) {
   return React.useCallback(fn, []);
 }
 
+function useIsMountedRef() {
+  const isMountedRef = React.useRef(true);
+  React.useLayoutEffect(
+    () => () => {
+      isMountedRef.current = false;
```
Comment (tom-sherman) [inline packages/reakit/src/Composite/CompositeState.ts]: I think I may be misunderstanding something but the conventions of the ref seem backwards to me.

We set isMounted = true, and then when react renders to the DOM for the first time (mound) we set it to false.

It would be great if you could add some comments to explain, unless what I'm missing/misunderstanding is painfully obvious to anyone who hasn't just woken up on a Monday morning!

Comment (diegohaz) [reply packages/reakit/src/Composite/CompositeState.ts]: It's setting isMounted to `false` in the return function of the effect callback, when the component is unmounted. Maybe setting `isUnmountedRef` to `true` would make more sense?

Comment (diegohaz) [reply packages/reakit/src/Composite/CompositeState.ts]: Added an explicit `return` statement, so hopefully it's more clear:
```js
function useIsUnmountedRef() {
  const isUnmountedRef = React.useRef(false);
  useIsomorphicEffect(() => {
    return () => {
      isUnmountedRef.current = true;
    };
  }, []);
  return isUnmountedRef;
}
```

Comment (tom-sherman) [reply packages/reakit/src/Composite/CompositeState.ts]: That is exactly what I was missing, makes sense!

**Comment by tom-sherman** [comment]
@diegohaz have you been able to get the codesandbox to work for this to verify it fixes the gutenberg issue? I'm getting a `ModuleNotFoundError` related to @wordpress/is-shallow-equal

**Comment by diegohaz** [comment]
I get the same error! But I was able to fork it and run locally. I think that's a bug on CodeSandbox, maybe related to https://github.com/codesandbox/codesandbox-client/issues/3782
