### PR TITLE
fix: Fix `disabled` prop being passed to elements that don't support it

### LINKED ISSUE #722: [Button] As 'a' with disabled prop focuses on `tab`
### Current behavior

image

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/button-with-a-disabled-bug-7znw8
2. Press Tab on the preview to see the button focus when keyboard press but not on pointer press.
3. Expect to see the button getting focused.

### Expected behavior

Button should not be focusable at all when `disabled`

### Possible solutions

```
const [isLink, setIsLink] = React.useState(false);

React.useEffect(() => {
      const element = ref.current;
      if (!isButton(element)) {
       if(element.tagName === "A") {
          setIsLink(true)
       }
     }
    }, []);

return {
   href: isLink & disabled ? undefined : htmlHref
}
```

### PR DESCRIPTION
**Pull request by navin-moorthy**
Closes #722 

As discussed in the above issue, I have conditionally removed the `disabled` prop from being returned to `a`, `audio` and `video` tags.

And `tabindex={-1}` when they are disabled and it works.

Added some examples as storybook to check the behaviour, I can remove them once the solution is valid

### CODE REVIEW

File: packages/reakit/src/Tabbable/Tabbable.ts [hunk 1]
```diff
@@ -120,6 +120,15 @@ function isNativeTabbable(element: Element) {
...
 
+function getHasDisabled(element: Element) {
+  return (
+    element.tagName === "BUTTON" ||
+    element.tagName === "INPUT" ||
+    element.tagName === "SELECT" ||
+    element.tagName === "TEXTAREA"
+  );
+}
+
```
Comment (diegohaz) [inline packages/reakit/src/Tabbable/Tabbable.ts]: I think `supportsDisabledAttribute` would be a better name. What do you think?

File: packages/reakit/src/Tabbable/Tabbable.ts [hunk 2]
```diff
@@ -145,6 +154,7 @@ export const useTabbable = createHook<TabbableOptions, TabbableHTMLProps>({
     const onMouseDownRef = useLiveRef(htmlOnMouseDown);
     const trulyDisabled = options.disabled && !options.focusable;
     const [nativeTabbable, setNativeTabbable] = React.useState(true);
+    const [hasDisabled, setHasDisabled] = React.useState(false);
```
Comment (diegohaz) [inline packages/reakit/src/Tabbable/Tabbable.ts]: Let's set it to `true` by default since Tabbable is used mostly for buttons, so we can avoid an additional render.

File: packages/reakit/src/Tabbable/Tabbable.ts [hunk 3]
```diff
@@ -195,8 +208,9 @@ export const useTabbable = createHook<TabbableOptions, TabbableHTMLProps>({
     return {
       ref: useForkRef(ref, htmlRef),
       style,
-      tabIndex: !trulyDisabled ? tabIndex : undefined,
-      disabled: trulyDisabled && nativeTabbable ? true : undefined,
+      tabIndex: !trulyDisabled ? tabIndex : !hasDisabled ? -1 : undefined,
```
Comment (diegohaz) [inline packages/reakit/src/Tabbable/Tabbable.ts]: This is also adding `tabIndex={-1}` to elements that aren't natively tabbable (like `div`s), making them focusable. I think this is why tests are failing.

```suggestion
      tabIndex: !trulyDisabled ? tabIndex : nativeTabbable && !hasDisabled ? -1 : undefined,
```

File: packages/reakit/src/Tabbable/Tabbable.ts (hunk 1 above)
Comment (navin-moorthy) [reply packages/reakit/src/Tabbable/Tabbable.ts]: I was thinking for a while and then later sticked to the current one.
Quite bad at naming !!
I will change it to `supportsDisabledAttribute`.

File: packages/reakit/src/Tabbable/Tabbable.ts (hunk 2 above)
Comment (navin-moorthy) [reply packages/reakit/src/Tabbable/Tabbable.ts]: Got it !!

File: packages/reakit/src/Tabbable/Tabbable.ts (hunk 3 above)
Comment (navin-moorthy) [reply packages/reakit/src/Tabbable/Tabbable.ts]: Sorry about that, I did not run the test but was only checking with the targetted examples.
I will improve this expression.
Thanks !!

**Comment by navin-moorthy** [comment]
> Thanks @navin-moorthy!
> 
> I made some suggestions. We can keep the examples, they're very useful. But I think they can be a single example (with `audio`, `a` and `video` elements) and could have some tests (see other examples).
> 
> I also noticed that some tests have failed. Not sure if it's really a regression or the tests aren't well written.

@diegohaz Sure, these were just some quick example for initial review. Glad to know that these examples were useful.
I will make it proper with tests on my next push.

**Comment by navin-moorthy** [comment]
@diegohaz All the test were successfull except this weird one. In the Example, in browser we wont be able to focus a link, but test expects it to be focused.

image

Need your assistance on this !!

**Comment by navin-moorthy** [comment]
> @diegohaz All the test were successfull except this weird one. In the Example, in browser we wont be able to focus a link, but test expects it to be focused.
> 
> image
> 
> Need your assistance on this !!

@diegohaz Do you have any idea on this how to proceed with this ? 🤔

**Comment by diegohaz** [comment]
I think we shouldn't be using `focus()` on those tests, but some interaction that the user would be able to do, like `press.Tab()` or `click()`. But I'll have a better look into this next weekend.

**Comment by navin-moorthy** [comment]
> I think we shouldn't be using `focus()` on those tests, but some interaction that the user would be able to do, like `press.Tab()` or `click()`. But I'll have a better look into this next weekend.

Thanks, I am not a testing person, haven't found myself time to learn.

**Comment by diegohaz** [comment]
Made some changes:

- Updated `Tabbable` so it just ignores `audio` and `video` tags. It should still work for people using `<Tabbable as="video">` (although I doubt someone is doing this). But it seems that there's no way to disable these elements without a really complex logic that's out of the scope of this component.
- Created a `getTabIndex` function to abstract the `tabIndex` logic and improve readability.
- Updated the example code to remove `audio` and `video` elements.
- Removed `Tabbable-test.tsx` and made tests against the example instead as we're trying to be more example-driven.

**Review by diegohaz — APPROVED** [review]
Thanks a lot @navin-moorthy!

I'll go ahead and merge it. But I would appreciate a review on the changes I made. If you find something wrong or that can be improved, we can iterate later.

**Comment by navin-moorthy** [comment]
Great !! Looks more organized @diegohaz and thanks.

Extracting `getTabIndex` utility saves some confusion within `useTabbable` 👌 .

I tested the components too, no issues.
