### PR TITLE
fix: Fix `form.reset()` not reverting array fields to initial state

### LINKED ISSUE #502: Form method `reset()` not working, Add FormResetButton
### Current behavior

Currently there isn't a button to use with `useFormState` to reset a form, similar to the existing submit, push and remove buttons. This means if you try to spread the form state on Reakit's `Button` element or a native HTML button element, you'll get numerous invalid prop errors, or you'll have to wire up individual props yourself.

If you manually call `form.reset()`, `form.values` does not get reset to `initialValues` as expected.

### Steps to reproduce the bug

Here's a Sandbox where the problem was observed:

https://codesandbox.io/s/codesadbox-prototyping-playground-lf0v3?fontsize=14&hidenavigation=1&initialpath=%2Fu&module=%2Fsrc%2Fpages%2FProfile%2FUserInfo%2FUserInfo.tsx&theme=dark

This should open the file containing the form as well as the page where the form is being used. Layout and logic are contained in `UserInfo.tsx`, styling of primitives are inside of `elements.ts`. Sorry for not providing a simpler example.

Let me know if you need any additional info!

### PR DESCRIPTION
**Pull request by diegohaz**
Closes #502

The problem was that the item was being `delete`d in the initial values as well. This PR copies the array using `Array.prototype.slice()`, which keeps empty items as empty.

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

File: packages/reakit/src/Form/FormState.ts [hunk 1]
```diff
@@ -264,7 +264,7 @@ function reducer<V>(
       };
     }
     case "remove": {
-      const array = unstable_getIn(state.values, action.name, []);
+      const array = unstable_getIn(state.values, action.name, []).slice();
```
Comment (tom-sherman) [inline packages/reakit/src/Form/FormState.ts:267]: The reason for the slice confused me for a while as I was expecting getIn to return a copy, like the Immutable.js method. Should this be the case?

Comment (diegohaz) [reply packages/reakit/src/Form/FormState.ts:267]: This is more like lodash's `get`, which doesn't return a copy. In fact, we could even use lodash there and things would still work.

This method is used in other places to get fields values. If it returned a different copy on every render I guess that would cause unnecessary re-renders.

Comment (tom-sherman) [reply packages/reakit/src/Form/FormState.ts:267]: Okay, cool!
