### PR TITLE
fix(Combobox): Fix badly positioned popover on click + minValueLength

### LINKED ISSUE #808: Combobox popover position is wrong when Combobox container is fixed/relative + minValueLength + input click
### Current behavior

When using the Combobox inside a container that is either fixed or relative, and using the minValueLength option: bad things happen. The positioning of the popover is wrong initially and once you validate an option will become OK.

(tested on chrome and safari latest, macOS bigsur)

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/zealous-sara-ljyyb?file=/src/App.tsx
2. **Click** on the input
3. Type "a"
4. Popover position is bad
5. Validate first result
6. Click again on the input
7. Popover position is good

**Demo:**
Kapture 2020-12-09 at 00 11 22

**How it's made:**
I replicated the Combobox fetch example (https://github.com/reakit/reakit/tree/master/packages/reakit/src/Combobox/__examples__/ComboboxFetch) and added:
- two containers to demonstrate the issue
- minValueLength: 1

### Expected behavior

Popover position should be good even if minValueLength: 1 is used and the container is fixed/relative

### Possible solutions

As discussed on Twitter, because this only happens on click (if you tab to the input: it works!) this might be an issue with the click handler of the input doing some unexpected changes compared to tab.

As a workaround, instead of using the minValueLength option, for now I am using:

```js
      <ComboboxPopover
        {...combobox}
        style={{
          visibility:
            combobox.inputValue.length < 1 || matches.length === 0
              ? "hidden"
              : "visible",
        }}
      >
```

Which seems to be "fine" but most probably not very aria friendly.

### Environment

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

  System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Memory: 51.84 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.20.0 - ~/.nvm/versions/node/v12.20.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.20.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 73.0.1
    Safari: 14.0.1
  npmPackages:
    react: 17.0.1 => 17.0.1
    react-dom: 17.0.1 => 17.0.1
    react-hook-form: 6.12.2 => 6.12.2
    react-loading-skeleton: 2.1.1 => 2.1.1
    react-script-hook: 1.2.1 => 1.2.1
    react-select-search: 2.2.3 => 2.2.3
    react-transition-group: 4.4.1 => 4.4.1
    react-use: 15.3.4 => 15.3.4
    reakit: 1.3.1 => 1.3.1
```

### PR DESCRIPTION
**Pull request by vvo**
Before this commit we were trying to show the Popover as soon as the user click
on the Combobox. This resulted in badly positioned Popover in some cases like
non-static Combobox containers.

Now we check if the Combobox value length is bigger than the minValueLength
before trying to show the Popover.

fixes #808

### CODE REVIEW

**Comment by vvo** [comment]
Hi @diegohaz, you had a good guess, this solves the issue.
I am not 100% confident my change is good but yes it does fix the issue (tested on the storybook).

Now I guess we need regression tests, again not sure where to start for that. Any pointers?

Finally, TypeScript is complaining here:
image

But I do not get why, since options.minValueLength defaults to 0 in the code already. Should I add a guard for that in case the user sends minValueLength: undefined?

Thanks!

File: packages/reakit/src/Combobox/Combobox.ts [hunk 1]
```diff
@@ -227,11 +227,19 @@ export const unstable_useCombobox = createHook<
       (event: React.MouseEvent<HTMLInputElement, MouseEvent>) => {
         onClickRef.current?.(event);
         if (event.defaultPrevented) return;
-        options.show?.();
+        if (value.length >= options.minValueLength) {
+          options.show?.();
+        }
```
Comment (diegohaz) [inline packages/reakit/src/Combobox/Combobox.ts]: I don't think we can add regression tests for this with JSDOM. Maybe with #733 in the future. For now, I'd say we should include a reference to the issue so people know what that line is solving.

```suggestion
        // https://github.com/reakit/reakit/issues/808
        if (!options.minValueLength || value.length >= options.minValueLength) {
          options.show?.();
        }
```

**Review by diegohaz — COMMENTED** [review]
Nice! Thanks for working on this, @vvo! I made a suggestion to get rid of the TS error.

**Comment by vvo** [comment]
> Nice! Thanks for working on this, @vvo! I made a suggestion to get rid of the TS error.

Thanks! I also had added this check to get rid of the TS error but removed it.

For my own curiosity: why is it even needed? Since in the code of reakit, minValueLength is always defined as 0 by default. I don't see why we need to defend against something that may not happen.

Unless the user uses useComboboxState({minValueLength: undefined}) maybe?

**Comment by diegohaz** [comment]
> For my own curiosity: why is it even needed? Since in the code of reakit, minValueLength is always defined as 0 by default. I don't see why we need to defend against something that may not happen.

In the current form, `minValueLength` may not be passed to `<Combobox />`. This will probably change in v2, but right now parts of the state can be omitted.

**Comment by diegohaz** [comment]
The CI is complaining about a changed file that hasn't been committed. I guess `yarn docs` should solve it.

**Comment by vvo** [comment]
(updated)

**Review by diegohaz — APPROVED** [review]
Nice! Thanks!
